const IMAGES = [
  "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=300&fit=crop",
  "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=300&h=300&fit=crop",
  "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=300&h=300&fit=crop",
  "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=300&fit=crop",
  "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=300&h=300&fit=crop",
  "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=300&h=400&fit=crop",
  "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=300&h=250&fit=crop",
  "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=300&h=350&fit=crop",
  "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=300&h=300&fit=crop",
];

export function SocialProof() {
  const doubled = [...IMAGES, ...IMAGES];

  return (
    <section className="py-24 overflow-hidden">
      <div className="text-center mb-12 px-6">
        <p className="text-white/30 text-sm font-medium">
          Generated by Aigencys — real results from real brands
        </p>
      </div>

      {/* Ticker row */}
      <div className="relative">
        {/* Fade edges */}
        <div className="absolute left-0 top-0 bottom-0 w-24 bg-gradient-to-r from-[#080808] to-transparent z-10 pointer-events-none" />
        <div className="absolute right-0 top-0 bottom-0 w-24 bg-gradient-to-l from-[#080808] to-transparent z-10 pointer-events-none" />

        <div className="flex gap-4 animate-ticker" style={{ width: "max-content" }}>
          {doubled.map((url, i) => (
            <div
              key={i}
              className="flex-shrink-0 w-52 h-52 rounded-2xl overflow-hidden"
            >
              <img
                src={url}
                alt="AI generated content"
                className="w-full h-full object-cover hover:scale-105 transition-transform duration-500"
              />
            </div>
          ))}
        </div>
      </div>

      {/* Brand logos */}
      <div className="flex items-center justify-center gap-12 mt-16 px-6 flex-wrap">
        {["Luxe Co.", "SportX", "Bloom Beauty", "Arch Studio", "Nova Tech"].map(
          (brand) => (
            <span
              key={brand}
              className="text-white/20 text-sm font-semibold tracking-wider uppercase hover:text-white/40 transition-colors"
            >
              {brand}
            </span>
          )
        )}
      </div>
    </section>
  );
}
